spring:
  datasource:
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    #    show-sql: true

  neo4j:
    uri: ${NEO4J_URI}
    authentication:
      username: ${NEO4J_USERNAME}
      password: ${NEO4J_PASSWORD}

cloud:
  aws:
    region:
      static: ap-northeast-2
    s3:
      bucket: ${AWS_BUCKET}
    stack:
      auto: false
    credentials:
      secret-key: ${AWS_SECRET_KEY}
      access-key: ${AWS_ACCESS_KEY}

logging:
  level:
    org:
      springframework:
        data:
          neo4j: DEBUG
      hibernate:
        SQL: DEBUG
